"""session

Revision ID: 19423810ab21
Revises: 2eda97871c9d
Create Date: 2020-11-14 15:46:06.120984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19423810ab21'
down_revision = '2eda97871c9d'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('session',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('last_online', sa.DateTime(), nullable=True),
	sa.Column('key', sa.String(length=36), nullable=True),
	sa.Column('data', sa.LargeBinary(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=True),
	sa.Column('agent', sa.String(length=255), nullable=False),
	sa.Column('expires_at', sa.DateTime(), nullable=False),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_session_created_at'), 'session', ['created_at'], unique=False)
	op.create_index(op.f('ix_session_expires_at'), 'session', ['expires_at'], unique=False)
	op.create_index(op.f('ix_session_key'), 'session', ['key'], unique=True)
	op.add_column('user', sa.Column('last_online', sa.DateTime(), nullable=True))
	op.drop_column('user', 'last_visit')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('user', sa.Column('last_visit', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
	op.drop_column('user', 'last_online')
	op.drop_index(op.f('ix_session_key'), table_name='session')
	op.drop_index(op.f('ix_session_expires_at'), table_name='session')
	op.drop_index(op.f('ix_session_created_at'), table_name='session')
	op.drop_table('session')
	# ### end Alembic commands ###
