"""comfortable from sa utils

Revision ID: 2396bda10371
Revises: b481458a743a
Create Date: 2020-11-16 11:33:06.264275

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2396bda10371'
down_revision = 'b481458a743a'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('user', sa.Column('backup_code_hashes', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
	op.drop_column('user', 'backup_code_hashes_string')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('user', sa.Column('backup_code_hashes_string', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
	op.drop_column('user', 'backup_code_hashes')
	# ### end Alembic commands ###
