"""add indexes where needed

Revision ID: 2eda97871c9d
Revises: 6ecb44c31e88
Create Date: 2020-11-10 12:45:44.708376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eda97871c9d'
down_revision = '6ecb44c31e88'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_index(op.f('ix_flask_dance_oauth_social_id'), 'flask_dance_oauth', ['social_id'], unique=False)
	op.create_index(op.f('ix_mail_token_created_at'), 'mail_token', ['created_at'], unique=False)
	op.create_index(op.f('ix_mail_token_key'), 'mail_token', ['key'], unique=True)
	op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
	op.create_index(op.f('ix_post_created_at'), 'post', ['created_at'], unique=False)
	op.create_index(op.f('ix_post_slug'), 'post', ['slug'], unique=True)
	op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
	op.create_index(op.f('ix_post_comment_created_at'), 'post_comment', ['created_at'], unique=False)
	op.create_index(op.f('ix_post_like_created_at'), 'post_like', ['created_at'], unique=False)
	op.create_index(op.f('ix_tag_created_at'), 'tag', ['created_at'], unique=False)
	op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
	op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
	op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
	op.create_index(op.f('ix_user_secret_key'), 'user', ['secret_key'], unique=True)
	op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_user_username'), table_name='user')
	op.drop_index(op.f('ix_user_secret_key'), table_name='user')
	op.drop_index(op.f('ix_user_email'), table_name='user')
	op.drop_index(op.f('ix_user_created_at'), table_name='user')
	op.drop_index(op.f('ix_tag_name'), table_name='tag')
	op.drop_index(op.f('ix_tag_created_at'), table_name='tag')
	op.drop_index(op.f('ix_post_like_created_at'), table_name='post_like')
	op.drop_index(op.f('ix_post_comment_created_at'), table_name='post_comment')
	op.drop_index(op.f('ix_post_title'), table_name='post')
	op.drop_index(op.f('ix_post_slug'), table_name='post')
	op.drop_index(op.f('ix_post_created_at'), table_name='post')
	op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
	op.drop_index(op.f('ix_mail_token_key'), table_name='mail_token')
	op.drop_index(op.f('ix_mail_token_created_at'), table_name='mail_token')
	op.drop_index(op.f('ix_flask_dance_oauth_social_id'), table_name='flask_dance_oauth')
	# ### end Alembic commands ###
