"""tag post m2m

Revision ID: 6cdbf5756eb8
Revises: a7977b26dc81
Create Date: 2020-10-27 11:13:01.347688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdbf5756eb8'
down_revision = 'a7977b26dc81'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('tag',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('name', sa.String(length=50), nullable=False),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('name')
	)
	op.create_table('post',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('author_id', sa.Integer(), nullable=False),
	sa.Column('image_filename', sa.String(length=50), nullable=True),
	sa.Column('title', sa.String(length=140), nullable=False),
	sa.Column('preview_text', sa.Text(), nullable=False),
	sa.Column('text', sa.Text(), nullable=False),
	sa.Column('slug', sa.String(length=175), nullable=False),
	sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('image_filename'),
	sa.UniqueConstraint('slug'),
	sa.UniqueConstraint('title', 'preview_text', 'text')
	)
	op.create_table('post_tag',
	sa.Column('post_id', sa.Integer(), nullable=False),
	sa.Column('tag_id', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
	sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
	sa.PrimaryKeyConstraint('post_id', 'tag_id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('post_tag')
	op.drop_table('post')
	op.drop_table('tag')
	# ### end Alembic commands ###
