"""postcomment

Revision ID: 6ecb44c31e88
Revises: f8d7ba9aeba1
Create Date: 2020-11-01 12:01:49.219996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecb44c31e88'
down_revision = 'f8d7ba9aeba1'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('post_comment',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('text', sa.Text(), nullable=False),
	sa.Column('author_id', sa.Integer(), nullable=False),
	sa.Column('post_id', sa.Integer(), nullable=False),
	sa.Column('parent_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
	sa.ForeignKeyConstraint(['parent_id'], ['post_comment.id'], ),
	sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('post_comment')
	# ### end Alembic commands ###
