"""oauth

Revision ID: 92e991128d06
Revises: 57243655f842
Create Date: 2020-10-23 12:00:17.373274

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '92e991128d06'
down_revision = '57243655f842'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('flask_dance_oauth',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('provider', sa.String(length=50), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=False),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('social_id', sa.String(length=255), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('flask_dance_oauth')
	# ### end Alembic commands ###
