"""notification

Revision ID: a7977b26dc81
Revises: 15fc7d8b77e4
Create Date: 2020-10-26 06:27:28.492578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7977b26dc81'
down_revision = '15fc7d8b77e4'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('notification',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('text', sa.Text(), nullable=False),
	sa.Column('is_checked', sa.Boolean(), nullable=True),
	sa.Column('recipient_id', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('notification')
	# ### end Alembic commands ###
