"""postlike

Revision ID: f8d7ba9aeba1
Revises: 6cdbf5756eb8
Create Date: 2020-11-01 09:34:12.776264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d7ba9aeba1'
down_revision = '6cdbf5756eb8'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('post_like',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('sender_id', sa.Integer(), nullable=False),
	sa.Column('post_id', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
	sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('sender_id', 'post_id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('post_like')
	# ### end Alembic commands ###
